#!/bin/bash

# Code generated by Gemini March 2026

# Check if exactly 3 arguments are provided
if [ "$#" -ne 3 ]; then
    echo "Usage: ./cpTemplate [type] [name] [location]"
    echo "Example: ./cpTemplate html myProject ~/Code"
    exit 1
fi

TYPE=$1
NAME=$2
LOCATION=$3

TEMPLATE_SRC="$HOME/.dotfiles/templates/$TYPE"
# Expand the tilde if the user provided one in the location argument
# LOCATION_EXPANDED="${LOCATION/#\~/$HOME}"
LOCATION_EXPANDED=$(realpath "$LOCATION")
DESTINATION="$LOCATION_EXPANDED/$NAME"

# 1. Check if the template exists
if [ ! -e "$TEMPLATE_SRC" ]; then
    echo "Error: Template type '$TYPE' not found in ~/.dotfiles/templates/"
    exit 1
fi

# 2. Ensure the parent directory of the location exists
if [ ! -d "$LOCATION_EXPANDED" ]; then
    echo "Location '$LOCATION' does not exist. Creating it now..."
    mkdir -p "$LOCATION_EXPANDED"
fi

# 3. Check if the destination already exists to prevent accidental overwrites
if [ -e "$DESTINATION" ]; then
    echo "Error: Destination '$DESTINATION' already exists."
    exit 1
fi

# 4. Perform the copy
# -r handles directories, -p preserves permissions
cp -rp "$TEMPLATE_SRC" "$DESTINATION"
cd "$DESTINATION"
